### ISSUE TITLE
# Sample State

### ISSUE THREAD

**Issue by andy-h-2016** [internetmara/FullStack#4]
- [x] State shape is flat!
- [x] State's keys are camelCased
- [x] All keys within the values in the state are accessible in the schema
- [x] Correctly formatted
- [x] Sample state is rendered with triple backticks, and the language `
javascript...
`). This will display the state as a code block instead of a giant line of text 
    - [x] Top level slices
        - [x] `entities`
        - [x] `session`
        - [x] `errors` (here or in `ui`)
        - [x] `ui` (if needed)
    - [x] Should NOT have nested slices, aka  `comments` inside of `posts`
      + Some info from other tables is ok, for instance:
        + the author username and imageurl for a post. basically any info that the user can't change
        + like count and a boolean on whether the user likes the post instead of a likes slice
## Comments

**Comment by andy-h-2016** [comment]
- If a dispensary can have multiple `types`, consider creating a joins table for `dispensaries` and `types` if it gets unwieldy. At the very least, make it an array of strings. So `["Medical", "Recreational"]` instead of `"Medical & Recreational"` 
- The state is in JS, so the keys should be camel case. `userId` instead of `user_id`

Otherwise looks great. Keep up the good work.

**Comment by internetmara** [comment]
There's only 3 types realistically. Medical, Recreational, & both. I'll do the array.

**Comment by andy-h-2016** [comment]
Closing this. Don't forget your `types` field can be just a string for simplicity.
