### ISSUE TITLE
# Frontend Routes

### ISSUE THREAD

**Issue by andy-h-2016** [internetmara/FullStack#6]
- [x] Frontend routes contains wildcard variables written in `camelCase`
- [x] Correctly formatted
    - [x] Routes are displayed with `inline coding text` (backticks)
## Comments

**Comment by andy-h-2016** [comment]
Probably want some sort of ProductIndex component for your dispensary show page. That may be what you're thinking when you say `DispensaryShow`. You also need a route & component for your map feature. And your cart/orders. 

Otherwise looks good.

**Comment by internetmara** [comment]
So there's a show page for all the dispensaries and then within each individual dispensary a show page for all the products, no?

**Comment by andy-h-2016** [comment]
within each individual dispensary will be a container (aka component) displaying all of its products. So I would move the `ProductIndex` component underneath the `DispensaryShow` component.

For your `OrderComponent` (aka your cart), since you want your cart to only have products from one dispensary, you probably want to look at how DoorDash does their shopping cart. If you order from one restaurant, and the cart will be empty when you jump to another restaurant's page.
